name: Build InfraSnow Downloader

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-14, macos-15]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: pyinstaller --console --onefile --icon assets/infrasnow.ico infrasnow_downloader.py

      - name: Archive Executable
        uses: actions/upload-artifact@v4
        with:
          name: infrasnow_downloader-${{ matrix.os }}
          path: dist/infrasnow_downloader*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Assets
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/artifacts
      - name: List Assets
        run: ls -lah ${{ github.workspace }}/artifacts/*
      - name: Compress Assets
        run: |
          zip -j ${{ github.workspace }}/artifacts/infrasnow_downloader-windows-latest.zip ${{ github.workspace }}/artifacts/infrasnow_downloader-windows-latest/infrasnow_downloader.exe
          cd ${{ github.workspace }}/artifacts/infrasnow_downloader-ubuntu-latest
          tar czf ${{ github.workspace }}/artifacts/infrasnow_downloader-ubuntu-latest.tar.gz infrasnow_downloader
          cd ${{ github.workspace }}/artifacts/infrasnow_downloader-macos-14
          tar czf ${{ github.workspace }}/artifacts/infrasnow_downloader-macos-14.tar.gz infrasnow_downloader
          cd ${{ github.workspace }}/artifacts/infrasnow_downloader-macos-15
          tar czf ${{ github.workspace }}/artifacts/infrasnow_downloader-macos-15.tar.gz infrasnow_downloader
      - name: Add Compressed Assets to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/artifacts/infrasnow_downloader*.*
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
