name: Build InfraSnow Downloader

on: 
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-14, macos-15]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller "pyserial==3.5"

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --console --onefile --icon assets/infrasnow.ico infrasnow_downloader.py

      - name: Archive Executable
        uses: actions/upload-artifact@v4
        with:
          name: infrasnow_downloader-${{ matrix.os }}
          path: |
            dist/infrasnow_downloader*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: /home/runner/work/infrasnow-download/infrasnow-download/infrasnow_downloader*/*
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
